apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:6.3.2
        name: logstash
        ports:
        - containerPort: 5044
          name: lumberjack
          protocol: TCP
        volumeMounts:
        - name: logstash-config-volume
          mountPath: /config
        command: [/usr/share/logstash/bin/logstash, -f, /config/logstash.config]
      volumes:
      - name: logstash-config-volume
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
  - port: 5044
  selector:
    app: logstash
